-- ============================================================================
-- Migration: enforce at most one directly-created visit per booking order
-- Scheduling + Package Management milestone.
--
-- create-requested-visit-from-booking.ts creates exactly one service_visits
-- row directly from a normal booking_orders row (the very first visit).
-- Later recurring visits for the same booking are generated by
-- generate-recurring-next-visit.ts and always carry a non-null
-- recurring_schedule_id, so this partial unique index — "at most one visit
-- per booking_order_id among visits with no recurring_schedule_id" —
-- targets exactly that one direct-creation case without blocking the
-- legitimate later recurring visits that share the same booking_order_id
-- for traceability. This is the DB-level backstop; the application layer
-- also does a find-before-insert check (see the repository), matching the
-- two-layer idempotency pattern used throughout this schema.
-- ============================================================================

create unique index service_visits_one_direct_visit_per_booking_order
  on public.service_visits (booking_order_id)
  where booking_order_id is not null and recurring_schedule_id is null;
